//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hoTools.hoSqlGui.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("hoTools.Query.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;EA-Matic
        ///&apos;Usage of Geert Bellekens Script Framework to administer Scripts recommended
        ///&apos;[path=\Framework\ho\hoTools]
        ///&apos;[group=hoTools]
        ///
        ///!INC Local Scripts.EAConstants-VBScript
        ///&apos;--------------------------------------------------------------------
        ///&apos; Demo Run SQL
        ///&apos; - Create VB Object 
        ///&apos;----------------------------------------------------------------------
        ///&apos; hoTools Script Environment
        ///&apos; Dim doesn&apos;t work (syntax error, used in EA for intellissense)
        ///&apos; Object &apos;Session&apos; doesn&apos;t exist (use  Repository.Wri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Clipboard {
            get {
                return ResourceManager.GetString("Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;EA-Matic
        ///&apos;[path=\Framework\ho\hoTools]
        ///&apos;[group=hoTools]
        ///!INC Local Scripts.EAConstants-VBScript
        ///
        ///&apos;--------------------------------------------------------------------
        ///&apos; hoTools Script Environment (Call from hoTools)
        ///&apos; - Global Key can run Script
        ///&apos; - Toolbar Button can run Script
        ///&apos; - SQL result rows can run Script 
        ///&apos;--------------------------------------------------------------------
        ///&apos; Dim doesn&apos;t work (syntax error)
        ///&apos; Object &apos;Session&apos; doesn&apos;t exist (use  Repository.WriteOutput &quot;Script&quot;, &quot;MyTest [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hoDemo2ParScript {
            get {
                return ResourceManager.GetString("hoDemo2ParScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //EA-Matic
        /////[path=\Framework\ho\hoTools]
        /////[group=hoTools]
        ///!INC Local Scripts.EAConstants-JScript
        ///
        ///
        /////----------------------------------------------------------------
        ///// hoTools Script environment:  Example of a JavaScript with two Parameters
        ///// Can be called from:
        ///// - SQL (Result rows)
        ///// - Global Key
        ///// - Toolbar
        /////
        ///// If you change a Script you have to update it by:
        ///// File, Update Scripts in hoTools Tab
        /////
        ///// 1.Parameter:  Context Item in EA (can be used as EA object)
        ///// 2. Parameter: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hoDemo2ParScript_JS {
            get {
                return ResourceManager.GetString("hoDemo2ParScript_JS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;EA-Matic
        ///&apos; Usage of Geert Bellekens Script Framework to administer Scripts recommended
        ///&apos;[path=\Framework\ho\hoTools]
        ///&apos;[group=hoTools]
        ///&apos;option explicit
        ///
        ///!INC Local Scripts.EAConstants-VBScript
        ///
        ///&apos;----------------------------------------------------------------------
        ///&apos; Dim doesn&apos;t work (syntax error, used in EA for intellissense)
        ///&apos; Object &apos;Session&apos; doesn&apos;t exist (use  rep.WriteOutput &quot;Script&quot;, &quot;MyTest&quot;,0)
        ///&apos; Var &apos;rep&apos; is loaded by script environment
        ///&apos; You may create an instance &apos;EAAddinFramework.Ut [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hoDemo3ParScript {
            get {
                return ResourceManager.GetString("hoDemo3ParScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&apos;EA-Matic
        ///&apos;[path=\Framework\ho\hoTools]
        ///&apos;[group=hoTools]
        ///!INC Local Scripts.EAConstants-VBScript
        ///
        ///&apos;--------------------------------------------------------------------
        ///&apos; hoTools Script Environment (Call from hoTools)
        ///&apos; - Global Key can run Script
        ///&apos; - Toolbar Button can run Script
        ///&apos; - SQL result rows can run Script 
        ///&apos;--------------------------------------------------------------------
        ///&apos; Dim doesn&apos;t work (syntax error)
        ///&apos; Object &apos;Session&apos; doesn&apos;t exist (use  Repository.WriteOutput &quot;Script&quot;, &quot;MyTe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hoDemoPrintContext {
            get {
                return ResourceManager.GetString("hoDemoPrintContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;EA-Matic
        ///&apos;Usage of Geert Bellekens Script Framework to administer Scripts recommended
        ///&apos;[path=\Framework\ho\hoTools]
        ///&apos;[group=hoTools]
        ///
        ///!INC Local Scripts.EAConstants-VBScript
        ///&apos;--------------------------------------------------------------------
        ///&apos; Demo Run SQL
        ///&apos; - Create VB Object 
        ///&apos;----------------------------------------------------------------------
        ///&apos; hoTools Script Environment
        ///&apos; Dim doesn&apos;t work (syntax error, used in EA for intellissense)
        ///&apos; Object &apos;Session&apos; doesn&apos;t exist (use  Repository.Wri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hoDemoRunSql {
            get {
                return ResourceManager.GetString("hoDemoRunSql", resourceCulture);
            }
        }
    }
}
