//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------

#pragma warning disable 1573, 1591

using System;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace hoLinqToSql.DataModels
{
    /// <summary>
    /// Database       : EABase
    /// Data Source    : EABase
    /// Server Version : 3.42.0
    /// </summary>
    public partial class EaDataModel : LinqToDB.Data.DataConnection
    {
        public ITable<t_attributeconstraints> t_attributeconstraints { get { return this.GetTable<t_attributeconstraints>(); } }
        public ITable<t_attributes> t_attribute { get { return this.GetTable<t_attributes>(); } }
        public ITable<t_attributetags> t_attributetag { get { return this.GetTable<t_attributetags>(); } }
        public ITable<t_authors> t_authors { get { return this.GetTable<t_authors>(); } }
        public ITable<t_cardinalities> t_cardinality { get { return this.GetTable<t_cardinalities>(); } }
        public ITable<t_categories> t_category { get { return this.GetTable<t_categories>(); } }
        public ITable<t_clients> t_clients { get { return this.GetTable<t_clients>(); } }
        public ITable<t_complexitytypes> t_complexitytypes { get { return this.GetTable<t_complexitytypes>(); } }
        public ITable<t_connectorconstraints> t_connectorconstraint { get { return this.GetTable<t_connectorconstraints>(); } }
        public ITable<t_connectors> t_connector { get { return this.GetTable<t_connectors>(); } }
        public ITable<t_connectortags> t_connectortag { get { return this.GetTable<t_connectortags>(); } }
        public ITable<t_connectortypes> t_connectortypes { get { return this.GetTable<t_connectortypes>(); } }
        public ITable<t_constants> t_constants { get { return this.GetTable<t_constants>(); } }
        public ITable<t_constrainttypes> t_constrainttypes { get { return this.GetTable<t_constrainttypes>(); } }
        public ITable<t_datatypes> t_datatypes { get { return this.GetTable<t_datatypes>(); } }
        public ITable<t_diagramlinks> t_diagramlinks { get { return this.GetTable<t_diagramlinks>(); } }
        public ITable<t_diagramobjects> t_diagramobjects { get { return this.GetTable<t_diagramobjects>(); } }
        public ITable<t_diagrams> t_diagram { get { return this.GetTable<t_diagrams>(); } }
        public ITable<t_diagramtypes> t_diagramtypes { get { return this.GetTable<t_diagramtypes>(); } }
        public ITable<t_documents> t_document { get { return this.GetTable<t_documents>(); } }
        public ITable<t_ecfs> t_ecf { get { return this.GetTable<t_ecfs>(); } }
        public ITable<t_efforttypes> t_efforttypes { get { return this.GetTable<t_efforttypes>(); } }
        public ITable<t_files> t_files { get { return this.GetTable<t_files>(); } }
        public ITable<t_genopts> t_genopt { get { return this.GetTable<t_genopts>(); } }
        public ITable<t_glossaries> t_glossary { get { return this.GetTable<t_glossaries>(); } }
        public ITable<t_htmls> t_html { get { return this.GetTable<t_htmls>(); } }
        public ITable<t_images> t_image { get { return this.GetTable<t_images>(); } }
        public ITable<t_implements> t_implement { get { return this.GetTable<t_implements>(); } }
        public ITable<t_issues> t_issues { get { return this.GetTable<t_issues>(); } }
        public ITable<t_lists> t_lists { get { return this.GetTable<t_lists>(); } }
        public ITable<t_mainttypes> t_mainttypes { get { return this.GetTable<t_mainttypes>(); } }
        public ITable<t_methods> t_method { get { return this.GetTable<t_methods>(); } }
        public ITable<t_metrictypes> t_metrictypes { get { return this.GetTable<t_metrictypes>(); } }
        public ITable<t_objectconstraints> t_objectconstraint { get { return this.GetTable<t_objectconstraints>(); } }
        public ITable<t_objectefforts> t_objecteffort { get { return this.GetTable<t_objectefforts>(); } }
        public ITable<t_objectfiles> t_objectfiles { get { return this.GetTable<t_objectfiles>(); } }
        public ITable<t_objectmetrics> t_objectmetrics { get { return this.GetTable<t_objectmetrics>(); } }
        public ITable<t_objectproblems> t_objectproblems { get { return this.GetTable<t_objectproblems>(); } }
        public ITable<t_objectproperties> t_objectproperties { get { return this.GetTable<t_objectproperties>(); } }
        public ITable<t_objectrequires> t_objectrequires { get { return this.GetTable<t_objectrequires>(); } }
        public ITable<t_objectresources> t_objectresource { get { return this.GetTable<t_objectresources>(); } }
        public ITable<t_objectrisks> t_objectrisks { get { return this.GetTable<t_objectrisks>(); } }
        public ITable<t_objects> t_object { get { return this.GetTable<t_objects>(); } }
        public ITable<t_objectscenarios> t_objectscenarios { get { return this.GetTable<t_objectscenarios>(); } }
        public ITable<t_objecttests> t_objecttests { get { return this.GetTable<t_objecttests>(); } }
        public ITable<t_objecttrxes> t_objecttrx { get { return this.GetTable<t_objecttrxes>(); } }
        public ITable<t_objecttypes> t_objecttypes { get { return this.GetTable<t_objecttypes>(); } }
        public ITable<t_ocfs> t_ocf { get { return this.GetTable<t_ocfs>(); } }
        public ITable<t_operationparams> t_operationparams { get { return this.GetTable<t_operationparams>(); } }
        public ITable<t_operationposts> t_operationposts { get { return this.GetTable<t_operationposts>(); } }
        public ITable<t_operationpres> t_operationpres { get { return this.GetTable<t_operationpres>(); } }
        public ITable<t_operations> t_operation { get { return this.GetTable<t_operations>(); } }
        public ITable<t_operationtags> t_operationtag { get { return this.GetTable<t_operationtags>(); } }
        public ITable<t_packages> t_package { get { return this.GetTable<t_packages>(); } }
        public ITable<t_paletteitems> t_paletteitem { get { return this.GetTable<t_paletteitems>(); } }
        public ITable<t_palettes> t_palette { get { return this.GetTable<t_palettes>(); } }
        public ITable<t_phases> t_phase { get { return this.GetTable<t_phases>(); } }
        public ITable<t_primitives> t_primitives { get { return this.GetTable<t_primitives>(); } }
        public ITable<t_problemtypes> t_problemtypes { get { return this.GetTable<t_problemtypes>(); } }
        public ITable<t_projectroles> t_projectroles { get { return this.GetTable<t_projectroles>(); } }
        public ITable<t_propertytypes> t_propertytypes { get { return this.GetTable<t_propertytypes>(); } }
        public ITable<t_requiretypes> t_requiretypes { get { return this.GetTable<t_requiretypes>(); } }
        public ITable<t_resources> t_resources { get { return this.GetTable<t_resources>(); } }
        public ITable<t_risktypes> t_risktypes { get { return this.GetTable<t_risktypes>(); } }
        public ITable<t_roleconstraints> t_roleconstraint { get { return this.GetTable<t_roleconstraints>(); } }
        public ITable<t_rtfreports> t_rtfreport { get { return this.GetTable<t_rtfreports>(); } }
        public ITable<t_rtfs> t_rtf { get { return this.GetTable<t_rtfs>(); } }
        public ITable<t_rules> t_rules { get { return this.GetTable<t_rules>(); } }
        public ITable<t_scenariotypes> t_scenariotypes { get { return this.GetTable<t_scenariotypes>(); } }
        public ITable<t_scripts> t_script { get { return this.GetTable<t_scripts>(); } }
        public ITable<t_secgrouppermissions> t_secgrouppermission { get { return this.GetTable<t_secgrouppermissions>(); } }
        public ITable<t_secgroups> t_secgroup { get { return this.GetTable<t_secgroups>(); } }
        public ITable<t_seclocks> t_seclocks { get { return this.GetTable<t_seclocks>(); } }
        public ITable<t_secpermissions> t_secpermission { get { return this.GetTable<t_secpermissions>(); } }
        public ITable<t_secpolicies> t_secpolicies { get { return this.GetTable<t_secpolicies>(); } }
        public ITable<t_secusergroups> t_secusergroup { get { return this.GetTable<t_secusergroups>(); } }
        public ITable<t_secuserpermissions> t_secuserpermission { get { return this.GetTable<t_secuserpermissions>(); } }
        public ITable<t_secusers> t_secuser { get { return this.GetTable<t_secusers>(); } }
        public ITable<t_snapshots> t_snapshot { get { return this.GetTable<t_snapshots>(); } }
        public ITable<t_statustypes> t_statustypes { get { return this.GetTable<t_statustypes>(); } }
        public ITable<t_stereotypes> t_stereotypes { get { return this.GetTable<t_stereotypes>(); } }
        public ITable<t_taggedvalues> t_taggedvalue { get { return this.GetTable<t_taggedvalues>(); } }
        public ITable<t_tasks> t_tasks { get { return this.GetTable<t_tasks>(); } }
        public ITable<t_tcfs> t_tcf { get { return this.GetTable<t_tcfs>(); } }
        public ITable<t_templates> t_template { get { return this.GetTable<t_templates>(); } }
        public ITable<t_testclasses> t_testclass { get { return this.GetTable<t_testclasses>(); } }
        public ITable<t_testplans> t_testplans { get { return this.GetTable<t_testplans>(); } }
        public ITable<t_testtypes> t_testtypes { get { return this.GetTable<t_testtypes>(); } }
        public ITable<t_trxtypes> t_trxtypes { get { return this.GetTable<t_trxtypes>(); } }
        public ITable<t_umlpatterns> t_umlpattern { get { return this.GetTable<t_umlpatterns>(); } }
        public ITable<t_versions> t_version { get { return this.GetTable<t_versions>(); } }
        public ITable<t_xrefs> t_xref { get { return this.GetTable<t_xrefs>(); } }
        public ITable<t_xrefsystems> t_xrefsystem { get { return this.GetTable<t_xrefsystems>(); } }
        public ITable<t_xrefusers> t_xrefuser { get { return this.GetTable<t_xrefusers>(); } }
        public ITable<usys_schemata> usys_schema { get { return this.GetTable<usys_schemata>(); } }
        public ITable<usys_systems> usys_system { get { return this.GetTable<usys_systems>(); } }
        public ITable<usysOldTables> usysOldTables { get { return this.GetTable<usysOldTables>(); } }
        public ITable<usysQueries> usysQueries { get { return this.GetTable<usysQueries>(); } }
        public ITable<usysTables> usysTables { get { return this.GetTable<usysTables>(); } }

        public EaDataModel()
        {
            InitDataContext();
            InitMappingSchema();
        }

        public EaDataModel(string configuration)
            : base(configuration)
        {
            InitDataContext();
            InitMappingSchema();
        }

        public EaDataModel(DataOptions options)
            : base(options)
        {
            InitDataContext();
            InitMappingSchema();
        }

        public EaDataModel(DataOptions<DataModels.EaDataModel> options)
            : base(options.Options)
        {
            InitDataContext();
            InitMappingSchema();
        }

        partial void InitDataContext();
        partial void InitMappingSchema();
    }

    [Table("t_attributeconstraints")]
    public partial class t_attributeconstraints
    {
        [Column, Nullable] public long? Object_ID { get; set; } // integer
        [PrimaryKey(0), NotNull] public string Constraint { get; set; } // text(max)
        [Column, Nullable] public string AttName { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [PrimaryKey(1), NotNull] public long ID { get; set; } // integer
    }

    [Table("t_attribute")]
    public partial class t_attributes
    {
        [Column, Nullable] public long? Object_ID { get; set; } // integer
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Scope { get; set; } // text(max)
        [Column, Nullable] public string Stereotype { get; set; } // text(max)
        [Column, Nullable] public string Containment { get; set; } // text(max)
        [Column, Nullable] public long? IsStatic { get; set; } // integer
        [Column, Nullable] public long? IsCollection { get; set; } // integer
        [Column, Nullable] public long? IsOrdered { get; set; } // integer
        [Column, Nullable] public long? AllowDuplicates { get; set; } // integer
        [Column, Nullable] public string LowerBound { get; set; } // text(max)
        [Column, Nullable] public string UpperBound { get; set; } // text(max)
        [Column, Nullable] public string Container { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Derived { get; set; } // text(max)
        [PrimaryKey, Identity] public long ID { get; set; } // integer
        [Column, Nullable] public long? Pos { get; set; } // integer
        [Column, Nullable] public string GenOption { get; set; } // text(max)
        [Column, Nullable] public long? Length { get; set; } // integer
        [Column, Nullable] public long? Precision { get; set; } // integer
        [Column, Nullable] public long? Scale { get; set; } // integer
        [Column, Nullable] public long? Const { get; set; } // integer
        [Column, Nullable] public string Style { get; set; } // text(max)
        [Column, Nullable] public string Classifier { get; set; } // text(max)
        [Column, Nullable] public string Default { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
        [Column, Nullable] public string StyleEx { get; set; } // text(max)
    }

    [Table("t_attributetag")]
    public partial class t_attributetags
    {
        [PrimaryKey, Identity] public long PropertyID { get; set; } // integer
        [Column, Nullable] public long? ElementID { get; set; } // integer
        [Column, Nullable] public string Property { get; set; } // text(max)
        [Column, Nullable] public string VALUE { get; set; } // text(max)
        [Column, Nullable] public string NOTES { get; set; } // text(max)
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
    }

    [Table("t_authors")]
    public partial class t_authors
    {
        [PrimaryKey, NotNull] public string AuthorName { get; set; } // text(max)
        [Column, Nullable] public string Roles { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_cardinality")]
    public partial class t_cardinalities
    {
        [PrimaryKey, NotNull] public string Cardinality { get; set; } // text(max)
    }

    [Table("t_category")]
    public partial class t_categories
    {
        [PrimaryKey, Identity] public long CategoryID { get; set; } // integer
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string NOTES { get; set; } // text(max)
    }

    [Table("t_clients")]
    public partial class t_clients
    {
        [PrimaryKey, NotNull] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Organisation { get; set; } // text(max)
        [Column, Nullable] public string Phone1 { get; set; } // text(max)
        [Column, Nullable] public string Phone2 { get; set; } // text(max)
        [Column, Nullable] public string Mobile { get; set; } // text(max)
        [Column, Nullable] public string Fax { get; set; } // text(max)
        [Column, Nullable] public string Email { get; set; } // text(max)
        [Column, Nullable] public string Roles { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_complexitytypes")]
    public partial class t_complexitytypes
    {
        [PrimaryKey, NotNull] public string Complexity { get; set; } // text(max)
        [Column, Nullable] public long? NumericWeight { get; set; } // integer
    }

    [Table("t_connectorconstraint")]
    public partial class t_connectorconstraints
    {
        [PrimaryKey(0), NotNull] public long ConnectorID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string Constraint { get; set; } // text(max)
        [Column, Nullable] public string ConstraintType { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_connector")]
    public partial class t_connectors
    {
        [PrimaryKey, Identity] public long Connector_ID { get; set; } // integer
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Direction { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Connector_Type { get; set; } // text(max)
        [Column, Nullable] public string SubType { get; set; } // text(max)
        [Column, Nullable] public string SourceCard { get; set; } // text(max)
        [Column, Nullable] public string SourceAccess { get; set; } // text(max)
        [Column, Nullable] public string SourceElement { get; set; } // text(max)
        [Column, Nullable] public string DestCard { get; set; } // text(max)
        [Column, Nullable] public string DestAccess { get; set; } // text(max)
        [Column, Nullable] public string DestElement { get; set; } // text(max)
        [Column, Nullable] public string SourceRole { get; set; } // text(max)
        [Column, Nullable] public string SourceRoleType { get; set; } // text(max)
        [Column, Nullable] public string SourceRoleNote { get; set; } // text(max)
        [Column, Nullable] public string SourceContainment { get; set; } // text(max)
        [Column, Nullable] public long? SourceIsAggregate { get; set; } // integer
        [Column, Nullable] public long? SourceIsOrdered { get; set; } // integer
        [Column, Nullable] public string SourceQualifier { get; set; } // text(max)
        [Column, Nullable] public string DestRole { get; set; } // text(max)
        [Column, Nullable] public string DestRoleType { get; set; } // text(max)
        [Column, Nullable] public string DestRoleNote { get; set; } // text(max)
        [Column, Nullable] public string DestContainment { get; set; } // text(max)
        [Column, Nullable] public long? DestIsAggregate { get; set; } // integer
        [Column, Nullable] public long? DestIsOrdered { get; set; } // integer
        [Column, Nullable] public string DestQualifier { get; set; } // text(max)
        [Column, Nullable] public long? Start_Object_ID { get; set; } // integer
        [Column, Nullable] public long? End_Object_ID { get; set; } // integer
        [Column, Nullable] public string Top_Start_Label { get; set; } // text(max)
        [Column, Nullable] public string Top_Mid_Label { get; set; } // text(max)
        [Column, Nullable] public string Top_End_Label { get; set; } // text(max)
        [Column, Nullable] public string Btm_Start_Label { get; set; } // text(max)
        [Column, Nullable] public string Btm_Mid_Label { get; set; } // text(max)
        [Column, Nullable] public string Btm_End_Label { get; set; } // text(max)
        [Column, Nullable] public long? Start_Edge { get; set; } // integer
        [Column, Nullable] public long? End_Edge { get; set; } // integer
        [Column, Nullable] public long? PtStartX { get; set; } // integer
        [Column, Nullable] public long? PtStartY { get; set; } // integer
        [Column, Nullable] public long? PtEndX { get; set; } // integer
        [Column, Nullable] public long? PtEndY { get; set; } // integer
        [Column, Nullable] public long? SeqNo { get; set; } // integer
        [Column, Nullable] public long? HeadStyle { get; set; } // integer
        [Column, Nullable] public long? LineStyle { get; set; } // integer
        [Column, Nullable] public long? RouteStyle { get; set; } // integer
        [Column, Nullable] public long? IsBold { get; set; } // integer
        [Column, Nullable] public long? LineColor { get; set; } // integer
        [Column, Nullable] public string Stereotype { get; set; } // text(max)
        [Column, Nullable] public string VirtualInheritance { get; set; } // text(max)
        [Column, Nullable] public string LinkAccess { get; set; } // text(max)
        [Column, Nullable] public string PDATA1 { get; set; } // text(max)
        [Column, Nullable] public string PDATA2 { get; set; } // text(max)
        [Column, Nullable] public string PDATA3 { get; set; } // text(max)
        [Column, Nullable] public string PDATA4 { get; set; } // text(max)
        [Column, Nullable] public string PDATA5 { get; set; } // text(max)
        [Column, Nullable] public long? DiagramID { get; set; } // integer
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
        [Column, Nullable] public string SourceConstraint { get; set; } // text(max)
        [Column, Nullable] public string DestConstraint { get; set; } // text(max)
        [Column, Nullable] public long? SourceIsNavigable { get; set; } // integer
        [Column, Nullable] public long? DestIsNavigable { get; set; } // integer
        [Column, Nullable] public long? IsRoot { get; set; } // integer
        [Column, Nullable] public long? IsLeaf { get; set; } // integer
        [Column, Nullable] public long? IsSpec { get; set; } // integer
        [Column, Nullable] public string SourceChangeable { get; set; } // text(max)
        [Column, Nullable] public string DestChangeable { get; set; } // text(max)
        [Column, Nullable] public string SourceTS { get; set; } // text(max)
        [Column, Nullable] public string DestTS { get; set; } // text(max)
        [Column, Nullable] public string StateFlags { get; set; } // text(max)
        [Column, Nullable] public string ActionFlags { get; set; } // text(max)
        [Column, Nullable] public long? IsSignal { get; set; } // integer
        [Column, Nullable] public long? IsStimulus { get; set; } // integer
        [Column, Nullable] public string DispatchAction { get; set; } // text(max)
        [Column, Nullable] public long? Target2 { get; set; } // integer
        [Column, Nullable] public string StyleEx { get; set; } // text(max)
        [Column, Nullable] public string SourceStereotype { get; set; } // text(max)
        [Column, Nullable] public string DestStereotype { get; set; } // text(max)
        [Column, Nullable] public string SourceStyle { get; set; } // text(max)
        [Column, Nullable] public string DestStyle { get; set; } // text(max)
        [Column, Nullable] public string EventFlags { get; set; } // text(max)
    }

    [Table("t_connectortag")]
    public partial class t_connectortags
    {
        [PrimaryKey, Identity] public long PropertyID { get; set; } // integer
        [Column, Nullable] public long? ElementID { get; set; } // integer
        [Column, Nullable] public string Property { get; set; } // text(max)
        [Column, Nullable] public string VALUE { get; set; } // text(max)
        [Column, Nullable] public string NOTES { get; set; } // text(max)
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
    }

    [Table("t_connectortypes")]
    public partial class t_connectortypes
    {
        [PrimaryKey, NotNull] public string Connector_Type { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
    }

    [Table("t_constants")]
    public partial class t_constants
    {
        [PrimaryKey, NotNull] public string ConstantName { get; set; } // text(max)
        [Column, Nullable] public string ConstantValue { get; set; } // text(max)
    }

    [Table("t_constrainttypes")]
    public partial class t_constrainttypes
    {
        [PrimaryKey, NotNull] public string Constraint { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_datatypes")]
    public partial class t_datatypes
    {
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string ProductName { get; set; } // text(max)
        [Column, Nullable] public string DataType { get; set; } // text(max)
        [Column, Nullable] public long? Size { get; set; } // integer
        [Column, Nullable] public long? MaxLen { get; set; } // integer
        [Column, Nullable] public long? MaxPrec { get; set; } // integer
        [Column, Nullable] public long? MaxScale { get; set; } // integer
        [Column, Nullable] public long? DefaultLen { get; set; } // integer
        [Column, Nullable] public long? DefaultPrec { get; set; } // integer
        [Column, Nullable] public long? DefaultScale { get; set; } // integer
        [Column, Nullable] public long? User { get; set; } // integer
        [Column, Nullable] public string PDATA1 { get; set; } // text(max)
        [Column, Nullable] public string PDATA2 { get; set; } // text(max)
        [Column, Nullable] public string PDATA3 { get; set; } // text(max)
        [Column, Nullable] public string PDATA4 { get; set; } // text(max)
        [Column, Nullable] public string HasLength { get; set; } // text(max)
        [Column, Nullable] public string GenericType { get; set; } // text(max)
        [PrimaryKey, Identity] public long DatatypeID { get; set; } // integer
    }

    [Table("t_diagramlinks")]
    public partial class t_diagramlinks
    {
        [Column, Nullable] public long? DiagramID { get; set; } // integer
        [Column, Nullable] public long? ConnectorID { get; set; } // integer
        [Column, Nullable] public string Geometry { get; set; } // text(max)
        [Column, Nullable] public string Style { get; set; } // text(max)
        [Column, NotNull] public long Hidden { get; set; } // integer
        [Column, Nullable] public string Path { get; set; } // text(max)
        [PrimaryKey, Identity] public long Instance_ID { get; set; } // integer
    }

    [Table("t_diagramobjects")]
    public partial class t_diagramobjects
    {
        [Column, Nullable] public long? Diagram_ID { get; set; } // integer
        [Column, Nullable] public long? Object_ID { get; set; } // integer
        [Column, Nullable] public long? RectTop { get; set; } // integer
        [Column, Nullable] public long? RectLeft { get; set; } // integer
        [Column, Nullable] public long? RectRight { get; set; } // integer
        [Column, Nullable] public long? RectBottom { get; set; } // integer
        [Column, Nullable] public long? Sequence { get; set; } // integer
        [Column, Nullable] public string ObjectStyle { get; set; } // text(max)
        [PrimaryKey, Identity] public long Instance_ID { get; set; } // integer
    }

    [Table("t_diagram")]
    public partial class t_diagrams
    {
        [PrimaryKey, Identity] public long Diagram_ID { get; set; } // integer
        [Column, Nullable] public long? Package_ID { get; set; } // integer
        [Column, Nullable] public long? ParentID { get; set; } // integer
        [Column, Nullable] public string Diagram_Type { get; set; } // text(max)
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Version { get; set; } // text(max)
        [Column, Nullable] public string Author { get; set; } // text(max)
        [Column, Nullable] public long? ShowDetails { get; set; } // integer
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Stereotype { get; set; } // text(max)
        [Column, NotNull] public long AttPub { get; set; } // integer
        [Column, NotNull] public long AttPri { get; set; } // integer
        [Column, NotNull] public long AttPro { get; set; } // integer
        [Column, Nullable] public string Orientation { get; set; } // text(max)
        [Column, Nullable] public long? cx { get; set; } // integer
        [Column, Nullable] public long? cy { get; set; } // integer
        [Column, Nullable] public long? Scale { get; set; } // integer
        [Column, Nullable] public string CreatedDate { get; set; } // text(max)
        [Column, Nullable] public string ModifiedDate { get; set; } // text(max)
        [Column, Nullable] public string HTMLPath { get; set; } // text(max)
        [Column, NotNull] public long ShowForeign { get; set; } // integer
        [Column, NotNull] public long ShowBorder { get; set; } // integer
        [Column, NotNull] public long ShowPackageContents { get; set; } // integer
        [Column, Nullable] public string PDATA { get; set; } // text(max)
        [Column, NotNull] public long Locked { get; set; } // integer
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
        [Column, Nullable] public long? TPos { get; set; } // integer
        [Column, Nullable] public string Swimlanes { get; set; } // text(max)
        [Column, Nullable] public string StyleEx { get; set; } // text(max)
    }

    [Table("t_diagramtypes")]
    public partial class t_diagramtypes
    {
        [PrimaryKey, NotNull] public string Diagram_Type { get; set; } // text(max)
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public long? Package_ID { get; set; } // integer
    }

    [Table("t_document")]
    public partial class t_documents
    {
        [PrimaryKey, NotNull] public string DocID { get; set; } // text(max)
        [Column, Nullable] public string DocName { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Style { get; set; } // text(max)
        [Column, NotNull] public string ElementID { get; set; } // text(max)
        [Column, NotNull] public string ElementType { get; set; } // text(max)
        [Column, Nullable] public string StrContent { get; set; } // text(max)
        [Column, Nullable] public byte[] BinContent { get; set; } // blob
        [Column, Nullable] public string DocType { get; set; } // text(max)
        [Column, Nullable] public string Author { get; set; } // text(max)
        [Column, Nullable] public string Version { get; set; } // text(max)
        [Column, Nullable] public long? IsActive { get; set; } // integer
        [Column, Nullable] public long? Sequence { get; set; } // integer
        [Column, Nullable] public string DocDate { get; set; } // text(max)
    }

    [Table("t_ecf")]
    public partial class t_ecfs
    {
        [PrimaryKey, NotNull] public string ECFID { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public double? Weight { get; set; } // real
        [Column, Nullable] public double? Value { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_efforttypes")]
    public partial class t_efforttypes
    {
        [PrimaryKey, NotNull] public string EffortType { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public double? NumericWeight { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_files")]
    public partial class t_files
    {
        [PrimaryKey, NotNull] public string FileID { get; set; } // text(max)
        [Column, Nullable] public string AppliesTo { get; set; } // text(max)
        [Column, Nullable] public string Category { get; set; } // text(max)
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string File { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string FileDate { get; set; } // text(max)
        [Column, Nullable] public long? FileSize { get; set; } // integer
    }

    [Table("t_genopt")]
    public partial class t_genopts
    {
        [Column, Nullable] public string AppliesTo { get; set; } // text(max)
        [Column, Nullable] public string Option { get; set; } // text(max)
    }

    [Table("t_glossary")]
    public partial class t_glossaries
    {
        [Column, Nullable] public string Term { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string Meaning { get; set; } // text(max)
        [PrimaryKey, Identity] public long GlossaryID { get; set; } // integer
    }

    [Table("t_html")]
    public partial class t_htmls
    {
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string Template { get; set; } // text(max)
    }

    [Table("t_image")]
    public partial class t_images
    {
        [PrimaryKey, Identity] public long ImageID { get; set; } // integer
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public byte[] Image { get; set; } // blob
    }

    [Table("t_implement")]
    public partial class t_implements
    {
        [Column, Nullable] public string Type { get; set; } // text(max)
    }

    [Table("t_issues")]
    public partial class t_issues
    {
        [Column, Nullable] public string Issue { get; set; } // text(max)
        [Column, Nullable] public string IssueDate { get; set; } // text(max)
        [Column, Nullable] public string Owner { get; set; } // text(max)
        [Column, Nullable] public string Status { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Resolver { get; set; } // text(max)
        [Column, Nullable] public string DateResolved { get; set; } // text(max)
        [Column, Nullable] public string Resolution { get; set; } // text(max)
        [PrimaryKey, Identity] public long IssueID { get; set; } // integer
        [Column, Nullable] public string Category { get; set; } // text(max)
        [Column, Nullable] public string Priority { get; set; } // text(max)
        [Column, Nullable] public string Severity { get; set; } // text(max)
        [Column, Nullable] public string IssueType { get; set; } // text(max)
    }

    [Table("t_lists")]
    public partial class t_lists
    {
        [PrimaryKey, NotNull] public string ListID { get; set; } // text(max)
        [Column, Nullable] public string Category { get; set; } // text(max)
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public long? NVal { get; set; } // integer
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_mainttypes")]
    public partial class t_mainttypes
    {
        [PrimaryKey, NotNull] public string MaintType { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public double? NumericWeight { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_method")]
    public partial class t_methods
    {
        [PrimaryKey(0), NotNull] public long Object_ID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Scope { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
    }

    [Table("t_metrictypes")]
    public partial class t_metrictypes
    {
        [PrimaryKey, NotNull] public string Metric { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public double? NumericWeight { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_objectconstraint")]
    public partial class t_objectconstraints
    {
        [PrimaryKey(0), NotNull] public long Object_ID { get; set; } // integer
        [PrimaryKey(2), NotNull] public string Constraint { get; set; } // text(max)
        [PrimaryKey(1), NotNull] public string ConstraintType { get; set; } // text(max)
        [Column, Nullable] public double? Weight { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Status { get; set; } // text(max)
    }

    [Table("t_objecteffort")]
    public partial class t_objectefforts
    {
        [PrimaryKey(0), NotNull] public long Object_ID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string Effort { get; set; } // text(max)
        [Column, Nullable] public string EffortType { get; set; } // text(max)
        [Column, Nullable] public double? EValue { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_objectfiles")]
    public partial class t_objectfiles
    {
        [PrimaryKey(0), NotNull] public long Object_ID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string FileName { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string Note { get; set; } // text(max)
        [Column, Nullable] public string FileSize { get; set; } // text(max)
        [Column, Nullable] public string FileDate { get; set; } // text(max)
    }

    [Table("t_objectmetrics")]
    public partial class t_objectmetrics
    {
        [PrimaryKey(0), NotNull] public long Object_ID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string Metric { get; set; } // text(max)
        [Column, Nullable] public string MetricType { get; set; } // text(max)
        [Column, Nullable] public double? EValue { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_objectproblems")]
    public partial class t_objectproblems
    {
        [PrimaryKey(0), NotNull] public long Object_ID { get; set; } // integer
        [PrimaryKey(2), NotNull] public string Problem { get; set; } // text(max)
        [PrimaryKey(1), NotNull] public string ProblemType { get; set; } // text(max)
        [Column, Nullable] public string DateReported { get; set; } // text(max)
        [Column, Nullable] public string Status { get; set; } // text(max)
        [Column, Nullable] public string ProblemNotes { get; set; } // text(max)
        [Column, Nullable] public string ReportedBy { get; set; } // text(max)
        [Column, Nullable] public string ResolvedBy { get; set; } // text(max)
        [Column, Nullable] public string DateResolved { get; set; } // text(max)
        [Column, Nullable] public string Version { get; set; } // text(max)
        [Column, Nullable] public string ResolverNotes { get; set; } // text(max)
        [Column, Nullable] public string Priority { get; set; } // text(max)
        [Column, Nullable] public string Severity { get; set; } // text(max)
    }

    [Table("t_objectproperties")]
    public partial class t_objectproperties
    {
        [PrimaryKey, Identity] public long PropertyID { get; set; } // integer
        [Column, Nullable] public long? Object_ID { get; set; } // integer
        [Column, Nullable] public string Property { get; set; } // text(max)
        [Column, Nullable] public string Value { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
    }

    [Table("t_objectrequires")]
    public partial class t_objectrequires
    {
        [PrimaryKey, Identity] public long ReqID { get; set; } // integer
        [Column, Nullable] public long? Object_ID { get; set; } // integer
        [Column, Nullable] public string Requirement { get; set; } // text(max)
        [Column, Nullable] public string ReqType { get; set; } // text(max)
        [Column, Nullable] public string Status { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Stability { get; set; } // text(max)
        [Column, Nullable] public string Difficulty { get; set; } // text(max)
        [Column, Nullable] public string Priority { get; set; } // text(max)
        [Column, Nullable] public string LastUpdate { get; set; } // text(max)
    }

    [Table("t_objectresource")]
    public partial class t_objectresources
    {
        [PrimaryKey(0), NotNull] public long Object_ID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string Resource { get; set; } // text(max)
        [PrimaryKey(2), NotNull] public string Role { get; set; } // text(max)
        [Column, Nullable] public double? Time { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public long? PercentComplete { get; set; } // integer
        [Column, Nullable] public string DateStart { get; set; } // text(max)
        [Column, Nullable] public string DateEnd { get; set; } // text(max)
        [Column, Nullable] public string History { get; set; } // text(max)
        [Column, Nullable] public long? ExpectedHours { get; set; } // integer
        [Column, Nullable] public long? ActualHours { get; set; } // integer
    }

    [Table("t_objectrisks")]
    public partial class t_objectrisks
    {
        [PrimaryKey(0), NotNull] public long Object_ID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string Risk { get; set; } // text(max)
        [Column, Nullable] public string RiskType { get; set; } // text(max)
        [Column, Nullable] public double? EValue { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_object")]
    public partial class t_objects
    {
        [PrimaryKey, Identity] public long Object_ID { get; set; } // integer
        [Column, Nullable] public string Object_Type { get; set; } // text(max)
        [Column, Nullable] public long? Diagram_ID { get; set; } // integer
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Alias { get; set; } // text(max)
        [Column, Nullable] public string Author { get; set; } // text(max)
        [Column, Nullable] public string Version { get; set; } // text(max)
        [Column, Nullable] public string Note { get; set; } // text(max)
        [Column, Nullable] public long? Package_ID { get; set; } // integer
        [Column, Nullable] public string Stereotype { get; set; } // text(max)
        [Column, Nullable] public long? NType { get; set; } // integer
        [Column, Nullable] public string Complexity { get; set; } // text(max)
        [Column, Nullable] public long? Effort { get; set; } // integer
        [Column, Nullable] public string Style { get; set; } // text(max)
        [Column, Nullable] public long? Backcolor { get; set; } // integer
        [Column, Nullable] public long? BorderStyle { get; set; } // integer
        [Column, Nullable] public long? BorderWidth { get; set; } // integer
        [Column, Nullable] public long? Fontcolor { get; set; } // integer
        [Column, Nullable] public long? Bordercolor { get; set; } // integer
        [Column, Nullable] public string CreatedDate { get; set; } // text(max)
        [Column, Nullable] public string ModifiedDate { get; set; } // text(max)
        [Column, Nullable] public string Status { get; set; } // text(max)
        [Column, Nullable] public string Abstract { get; set; } // text(max)
        [Column, Nullable] public long? Tagged { get; set; } // integer
        [Column, Nullable] public string PDATA1 { get; set; } // text(max)
        [Column, Nullable] public string PDATA2 { get; set; } // text(max)
        [Column, Nullable] public string PDATA3 { get; set; } // text(max)
        [Column, Nullable] public string PDATA4 { get; set; } // text(max)
        [Column, Nullable] public string PDATA5 { get; set; } // text(max)
        [Column, Nullable] public string Concurrency { get; set; } // text(max)
        [Column, Nullable] public string Visibility { get; set; } // text(max)
        [Column, Nullable] public string Persistence { get; set; } // text(max)
        [Column, Nullable] public string Cardinality { get; set; } // text(max)
        [Column, Nullable] public string GenType { get; set; } // text(max)
        [Column, Nullable] public string GenFile { get; set; } // text(max)
        [Column, Nullable] public string Header1 { get; set; } // text(max)
        [Column, Nullable] public string Header2 { get; set; } // text(max)
        [Column, Nullable] public string Phase { get; set; } // text(max)
        [Column, Nullable] public string Scope { get; set; } // text(max)
        [Column, Nullable] public string GenOption { get; set; } // text(max)
        [Column, Nullable] public string GenLinks { get; set; } // text(max)
        [Column, Nullable] public long? Classifier { get; set; } // integer
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
        [Column, Nullable] public long? ParentID { get; set; } // integer
        [Column, Nullable] public string RunState { get; set; } // text(max)
        [Column, Nullable] public string Classifier_guid { get; set; } // text(max)
        [Column, Nullable] public long? TPos { get; set; } // integer
        [Column, Nullable] public long? IsRoot { get; set; } // integer
        [Column, Nullable] public long? IsLeaf { get; set; } // integer
        [Column, Nullable] public long? IsSpec { get; set; } // integer
        [Column, Nullable] public long? IsActive { get; set; } // integer
        [Column, Nullable] public string StateFlags { get; set; } // text(max)
        [Column, Nullable] public string PackageFlags { get; set; } // text(max)
        [Column, Nullable] public string Multiplicity { get; set; } // text(max)
        [Column, Nullable] public string StyleEx { get; set; } // text(max)
        [Column, Nullable] public string ActionFlags { get; set; } // text(max)
        [Column, Nullable] public string EventFlags { get; set; } // text(max)
    }

    [Table("t_objectscenarios")]
    public partial class t_objectscenarios
    {
        [PrimaryKey(0), NotNull] public long Object_ID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string Scenario { get; set; } // text(max)
        [Column, Nullable] public string ScenarioType { get; set; } // text(max)
        [Column, Nullable] public double? EValue { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string XMLContent { get; set; } // text(max)
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
    }

    [Table("t_objecttests")]
    public partial class t_objecttests
    {
        [PrimaryKey(0), NotNull] public long Object_ID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string Test { get; set; } // text(max)
        [PrimaryKey(2), NotNull] public long TestClass { get; set; } // integer
        [Column, Nullable] public string TestType { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string InputData { get; set; } // text(max)
        [Column, Nullable] public string AcceptanceCriteria { get; set; } // text(max)
        [Column, Nullable] public string Status { get; set; } // text(max)
        [Column, Nullable] public string DateRun { get; set; } // text(max)
        [Column, Nullable] public string Results { get; set; } // text(max)
        [Column, Nullable] public string RunBy { get; set; } // text(max)
        [Column, Nullable] public string CheckBy { get; set; } // text(max)
    }

    [Table("t_objecttrx")]
    public partial class t_objecttrxes
    {
        [PrimaryKey(0), NotNull] public long Object_ID { get; set; } // integer
        [PrimaryKey(2), NotNull] public string TRX { get; set; } // text(max)
        [PrimaryKey(1), NotNull] public string TRXType { get; set; } // text(max)
        [Column, Nullable] public double? Weight { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_objecttypes")]
    public partial class t_objecttypes
    {
        [PrimaryKey, NotNull] public string Object_Type { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public long? DesignObject { get; set; } // integer
        [Column, Nullable] public long? ImageID { get; set; } // integer
    }

    [Table("t_ocf")]
    public partial class t_ocfs
    {
        [Column, Nullable] public string ObjectType { get; set; } // text(max)
        [Column, Nullable] public double? ComplexityWeight { get; set; } // real
    }

    [Table("t_operationparams")]
    public partial class t_operationparams
    {
        [PrimaryKey(0), NotNull] public long OperationID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string Default { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public long? Pos { get; set; } // integer
        [Column, Nullable] public long? Const { get; set; } // integer
        [Column, Nullable] public string Style { get; set; } // text(max)
        [Column, Nullable] public string Kind { get; set; } // text(max)
        [Column, Nullable] public string Classifier { get; set; } // text(max)
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
        [Column, Nullable] public string StyleEx { get; set; } // text(max)
    }

    [Table("t_operationposts")]
    public partial class t_operationposts
    {
        [PrimaryKey(0), NotNull] public long OperationID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string PostCondition { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_operationpres")]
    public partial class t_operationpres
    {
        [PrimaryKey(0), NotNull] public long OperationID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string PreCondition { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_operation")]
    public partial class t_operations
    {
        [PrimaryKey, Identity] public long OperationID { get; set; } // integer
        [Column, Nullable] public long? Object_ID { get; set; } // integer
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Scope { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string ReturnArray { get; set; } // text(max)
        [Column, Nullable] public string Stereotype { get; set; } // text(max)
        [Column, Nullable] public string IsStatic { get; set; } // text(max)
        [Column, Nullable] public string Concurrency { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Behaviour { get; set; } // text(max)
        [Column, Nullable] public string Abstract { get; set; } // text(max)
        [Column, Nullable] public string GenOption { get; set; } // text(max)
        [Column, Nullable] public string Synchronized { get; set; } // text(max)
        [Column, Nullable] public long? Pos { get; set; } // integer
        [Column, Nullable] public long? Const { get; set; } // integer
        [Column, Nullable] public string Style { get; set; } // text(max)
        [Column, Nullable] public long? Pure { get; set; } // integer
        [Column, Nullable] public string Throws { get; set; } // text(max)
        [Column, Nullable] public string Classifier { get; set; } // text(max)
        [Column, Nullable] public string Code { get; set; } // text(max)
        [Column, Nullable] public long? IsRoot { get; set; } // integer
        [Column, Nullable] public long? IsLeaf { get; set; } // integer
        [Column, Nullable] public long? IsQuery { get; set; } // integer
        [Column, Nullable] public string StateFlags { get; set; } // text(max)
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
        [Column, Nullable] public string StyleEx { get; set; } // text(max)
    }

    [Table("t_operationtag")]
    public partial class t_operationtags
    {
        [PrimaryKey, Identity] public long PropertyID { get; set; } // integer
        [Column, Nullable] public long? ElementID { get; set; } // integer
        [Column, Nullable] public string Property { get; set; } // text(max)
        [Column, Nullable] public string VALUE { get; set; } // text(max)
        [Column, Nullable] public string NOTES { get; set; } // text(max)
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
    }

    [Table("t_package")]
    public partial class t_packages
    {
        [PrimaryKey, Identity] public long Package_ID { get; set; } // integer
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public long? Parent_ID { get; set; } // integer
        [Column, Nullable] public string CreatedDate { get; set; } // text(max)
        [Column, Nullable] public string ModifiedDate { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
        [Column, Nullable] public string XMLPath { get; set; } // text(max)
        [Column, Nullable] public long? IsControlled { get; set; } // integer
        [Column, Nullable] public string LastLoadDate { get; set; } // text(max)
        [Column, Nullable] public string LastSaveDate { get; set; } // text(max)
        [Column, Nullable] public string Version { get; set; } // text(max)
        [Column, Nullable] public long? Protected { get; set; } // integer
        [Column, Nullable] public string PkgOwner { get; set; } // text(max)
        [Column, Nullable] public string UMLVersion { get; set; } // text(max)
        [Column, Nullable] public long? UseDTD { get; set; } // integer
        [Column, Nullable] public long? LogXML { get; set; } // integer
        [Column, Nullable] public string CodePath { get; set; } // text(max)
        [Column, Nullable] public string Namespace { get; set; } // text(max)
        [Column, Nullable] public long? TPos { get; set; } // integer
        [Column, Nullable] public string PackageFlags { get; set; } // text(max)
        [Column, Nullable] public long? BatchSave { get; set; } // integer
        [Column, Nullable] public long? BatchLoad { get; set; } // integer
    }

    [Table("t_paletteitem")]
    public partial class t_paletteitems
    {
        [Column, Nullable] public long? PaletteID { get; set; } // integer
        [Column, Nullable] public long? ItemID { get; set; } // integer
    }

    [Table("t_palette")]
    public partial class t_palettes
    {
        [PrimaryKey, Identity] public long PaletteID { get; set; } // integer
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
    }

    [Table("t_phase")]
    public partial class t_phases
    {
        [PrimaryKey, NotNull] public string PhaseID { get; set; } // text(max)
        [Column, Nullable] public string PhaseName { get; set; } // text(max)
        [Column, Nullable] public string PhaseNotes { get; set; } // text(max)
        [Column, Nullable] public string PhaseStyle { get; set; } // text(max)
        [Column, Nullable] public string StartDate { get; set; } // text(max)
        [Column, Nullable] public string EndDate { get; set; } // text(max)
        [Column, Nullable] public string PhaseContent { get; set; } // text(max)
    }

    [Table("t_primitives")]
    public partial class t_primitives
    {
        [PrimaryKey, NotNull] public string Datatype { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
    }

    [Table("t_problemtypes")]
    public partial class t_problemtypes
    {
        [PrimaryKey, NotNull] public string ProblemType { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public double? NumericWeight { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_projectroles")]
    public partial class t_projectroles
    {
        [PrimaryKey, NotNull] public string Role { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_propertytypes")]
    public partial class t_propertytypes
    {
        [PrimaryKey, NotNull] public string Property { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_requiretypes")]
    public partial class t_requiretypes
    {
        [PrimaryKey, NotNull] public string Requirement { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public double? NumericWeight { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_resources")]
    public partial class t_resources
    {
        [PrimaryKey, NotNull] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Organisation { get; set; } // text(max)
        [Column, Nullable] public string Phone1 { get; set; } // text(max)
        [Column, Nullable] public string Phone2 { get; set; } // text(max)
        [Column, Nullable] public string Mobile { get; set; } // text(max)
        [Column, Nullable] public string Fax { get; set; } // text(max)
        [Column, Nullable] public string Email { get; set; } // text(max)
        [Column, Nullable] public string Roles { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_risktypes")]
    public partial class t_risktypes
    {
        [PrimaryKey, NotNull] public string Risk { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public double? NumericWeight { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_roleconstraint")]
    public partial class t_roleconstraints
    {
        [PrimaryKey(0), NotNull] public long ConnectorID { get; set; } // integer
        [PrimaryKey(1), NotNull] public string Constraint { get; set; } // text(max)
        [PrimaryKey(2), NotNull] public string ConnectorEnd { get; set; } // text(max)
        [PrimaryKey(3), NotNull] public string ConstraintType { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_rtfreport")]
    public partial class t_rtfreports
    {
        [PrimaryKey, NotNull] public string TemplateID { get; set; } // text(max)
        [Column, Nullable] public long? RootPackage { get; set; } // integer
        [Column, Nullable] public string Filename { get; set; } // text(max)
        [Column, Nullable] public long? Details { get; set; } // integer
        [Column, Nullable] public long? ProcessChildren { get; set; } // integer
        [Column, Nullable] public long? ShowDiagrams { get; set; } // integer
        [Column, Nullable] public string Heading { get; set; } // text(max)
        [Column, Nullable] public long? Requirements { get; set; } // integer
        [Column, Nullable] public long? Associations { get; set; } // integer
        [Column, Nullable] public long? Scenarios { get; set; } // integer
        [Column, Nullable] public long? ChildDiagrams { get; set; } // integer
        [Column, Nullable] public long? Attributes { get; set; } // integer
        [Column, Nullable] public long? Methods { get; set; } // integer
        [Column, Nullable] public long? ImageType { get; set; } // integer
        [Column, Nullable] public long? Paging { get; set; } // integer
        [Column, Nullable] public string Intro { get; set; } // text(max)
        [Column, Nullable] public long? Resources { get; set; } // integer
        [Column, Nullable] public long? Constraints { get; set; } // integer
        [Column, Nullable] public long? Tagged { get; set; } // integer
        [Column, Nullable] public long? ShowTag { get; set; } // integer
        [Column, Nullable] public long? ShowAlias { get; set; } // integer
        [Column, Nullable] public string PDATA1 { get; set; } // text(max)
        [Column, Nullable] public string PDATA2 { get; set; } // text(max)
        [Column, Nullable] public string PDATA3 { get; set; } // text(max)
        [Column, Nullable] public string PDATA4 { get; set; } // text(max)
    }

    [Table("t_rtf")]
    public partial class t_rtfs
    {
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string Template { get; set; } // text(max)
    }

    [Table("t_rules")]
    public partial class t_rules
    {
        [PrimaryKey, NotNull] public string RuleID { get; set; } // text(max)
        [Column, Nullable] public string RuleName { get; set; } // text(max)
        [Column, Nullable] public string RuleType { get; set; } // text(max)
        [Column, Nullable] public long? RuleActive { get; set; } // integer
        [Column, Nullable] public string ErrorMsg { get; set; } // text(max)
        [Column, Nullable] public string Flags { get; set; } // text(max)
        [Column, Nullable] public string RuleOCL { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string RuleXML { get; set; } // text(max)
    }

    [Table("t_scenariotypes")]
    public partial class t_scenariotypes
    {
        [PrimaryKey, NotNull] public string ScenarioType { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public double? NumericWeight { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_script")]
    public partial class t_scripts
    {
        [PrimaryKey, Identity] public long ScriptID { get; set; } // integer
        [Column, Nullable] public string ScriptCategory { get; set; } // text(max)
        [Column, Nullable] public string ScriptName { get; set; } // text(max)
        [Column, Nullable] public string ScriptAuthor { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Script { get; set; } // text(max)
    }

    [Table("t_secgrouppermission")]
    public partial class t_secgrouppermissions
    {
        [PrimaryKey(0), NotNull] public string GroupID { get; set; } // text(max)
        [PrimaryKey(1), NotNull] public long PermissionID { get; set; } // integer
    }

    [Table("t_secgroup")]
    public partial class t_secgroups
    {
        [PrimaryKey, NotNull] public string GroupID { get; set; } // text(max)
        [Column, Nullable] public string GroupName { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
    }

    [Table("t_seclocks")]
    public partial class t_seclocks
    {
        [Column, Nullable] public string UserID { get; set; } // text(max)
        [Column, Nullable] public string GroupID { get; set; } // text(max)
        [Column, Nullable] public string EntityType { get; set; } // text(max)
        [PrimaryKey, NotNull] public string EntityID { get; set; } // text(max)
        [Column, Nullable] public string Timestamp { get; set; } // text(max)
        [Column, Nullable] public string LockType { get; set; } // text(max)
    }

    [Table("t_secpermission")]
    public partial class t_secpermissions
    {
        [PrimaryKey, NotNull] public long PermissionID { get; set; } // integer
        [Column, Nullable] public string PermissionName { get; set; } // text(max)
    }

    [Table("t_secpolicies")]
    public partial class t_secpolicies
    {
        [PrimaryKey, NotNull] public string Property { get; set; } // text(max)
        [Column, Nullable] public string Value { get; set; } // text(max)
    }

    [Table("t_secusergroup")]
    public partial class t_secusergroups
    {
        [PrimaryKey(0), NotNull] public string UserID { get; set; } // text(max)
        [PrimaryKey(1), NotNull] public string GroupID { get; set; } // text(max)
    }

    [Table("t_secuserpermission")]
    public partial class t_secuserpermissions
    {
        [PrimaryKey(0), NotNull] public string UserID { get; set; } // text(max)
        [PrimaryKey(1), NotNull] public long PermissionID { get; set; } // integer
    }

    [Table("t_secuser")]
    public partial class t_secusers
    {
        [PrimaryKey, NotNull] public string UserID { get; set; } // text(max)
        [Column, Nullable] public string UserLogin { get; set; } // text(max)
        [Column, Nullable] public string FirstName { get; set; } // text(max)
        [Column, Nullable] public string Surname { get; set; } // text(max)
        [Column, Nullable] public string Department { get; set; } // text(max)
        [Column, Nullable] public string Password { get; set; } // text(max)
    }

    [Table("t_snapshot")]
    public partial class t_snapshots
    {
        [PrimaryKey, NotNull] public string SnapshotID { get; set; } // text(max)
        [Column, Nullable] public string SeriesID { get; set; } // text(max)
        [Column, Nullable] public long? Position { get; set; } // integer
        [Column, Nullable] public string SnapshotName { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Style { get; set; } // text(max)
        [Column, Nullable] public string ElementID { get; set; } // text(max)
        [Column, Nullable] public string ElementType { get; set; } // text(max)
        [Column, Nullable] public string StrContent { get; set; } // text(max)
        [Column, Nullable] public byte[] BinContent1 { get; set; } // blob
        [Column, Nullable] public byte[] BinContent2 { get; set; } // blob
    }

    [Table("t_statustypes")]
    public partial class t_statustypes
    {
        [PrimaryKey, NotNull] public string Status { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
    }

    [Table("t_stereotypes")]
    public partial class t_stereotypes
    {
        [PrimaryKey(1), NotNull] public string Stereotype { get; set; } // text(max)
        [PrimaryKey(0), NotNull] public string AppliesTo { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public long? MFEnabled { get; set; } // integer
        [Column, Nullable] public string MFPath { get; set; } // text(max)
        [Column, Nullable] public byte[] Metafile { get; set; } // blob
        [Column, Nullable] public string Style { get; set; } // text(max)
        [Column, Nullable] public string ea_guid { get; set; } // text(max)
        [Column, Nullable] public string VisualType { get; set; } // text(max)
    }

    [Table("t_taggedvalue")]
    public partial class t_taggedvalues
    {
        [PrimaryKey, NotNull] public string PropertyID { get; set; } // text(max)
        [Column, Nullable] public string ElementID { get; set; } // text(max)
        [Column, Nullable] public string BaseClass { get; set; } // text(max)
        [Column, Nullable] public string TagValue { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_tasks")]
    public partial class t_tasks
    {
        [PrimaryKey, Identity] public long TaskID { get; set; } // integer
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string TaskType { get; set; } // text(max)
        [Column, Nullable] public string NOTES { get; set; } // text(max)
        [Column, Nullable] public string Priority { get; set; } // text(max)
        [Column, Nullable] public string Status { get; set; } // text(max)
        [Column, Nullable] public string Owner { get; set; } // text(max)
        [Column, Nullable] public string StartDate { get; set; } // text(max)
        [Column, Nullable] public string EndDate { get; set; } // text(max)
        [Column, Nullable] public string Phase { get; set; } // text(max)
        [Column, Nullable] public string History { get; set; } // text(max)
        [Column, Nullable] public long? Percent { get; set; } // integer
        [Column, Nullable] public long? TotalTime { get; set; } // integer
        [Column, Nullable] public long? ActualTime { get; set; } // integer
        [Column, Nullable] public string AssignedTo { get; set; } // text(max)
    }

    [Table("t_tcf")]
    public partial class t_tcfs
    {
        [PrimaryKey, NotNull] public string TCFID { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public double? Weight { get; set; } // real
        [Column, Nullable] public double? Value { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_template")]
    public partial class t_templates
    {
        [PrimaryKey, NotNull] public string TemplateID { get; set; } // text(max)
        [Column, Nullable] public string TemplateType { get; set; } // text(max)
        [Column, Nullable] public string TemplateName { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Style { get; set; } // text(max)
        [Column, Nullable] public string Template { get; set; } // text(max)
    }

    [Table("t_testclass")]
    public partial class t_testclasses
    {
        [PrimaryKey, NotNull] public string TestClass { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
    }

    [Table("t_testplans")]
    public partial class t_testplans
    {
        [PrimaryKey, NotNull] public string PlanID { get; set; } // text(max)
        [Column, Nullable] public string Category { get; set; } // text(max)
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Author { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string TestPlan { get; set; } // text(max)
    }

    [Table("t_testtypes")]
    public partial class t_testtypes
    {
        [PrimaryKey, NotNull] public string TestType { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public double? NumericWeight { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
    }

    [Table("t_trxtypes")]
    public partial class t_trxtypes
    {
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public double? NumericWeight { get; set; } // real
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string TRX { get; set; } // text(max)
        [PrimaryKey, Identity] public long TRX_ID { get; set; } // integer
        [Column, Nullable] public string Style { get; set; } // text(max)
    }

    [Table("t_umlpattern")]
    public partial class t_umlpatterns
    {
        [PrimaryKey, Identity] public long PatternID { get; set; } // integer
        [Column, Nullable] public string PatternCategory { get; set; } // text(max)
        [Column, Nullable] public string PatternName { get; set; } // text(max)
        [Column, Nullable] public string Style { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string PatternXML { get; set; } // text(max)
        [Column, Nullable] public string Version { get; set; } // text(max)
    }

    [Table("t_version")]
    public partial class t_versions
    {
        [PrimaryKey(0), NotNull] public string ElementID { get; set; } // text(max)
        [PrimaryKey(1), NotNull] public string VersionID { get; set; } // text(max)
        [Column, Nullable] public string ElementType { get; set; } // text(max)
        [Column, Nullable] public string Flags { get; set; } // text(max)
        [Column, Nullable] public string ExternalFile { get; set; } // text(max)
        [Column, Nullable] public string Notes { get; set; } // text(max)
        [Column, Nullable] public string Owner { get; set; } // text(max)
        [Column, Nullable] public string VersionDate { get; set; } // text(max)
        [Column, Nullable] public string Branch { get; set; } // text(max)
        [Column, Nullable] public string ElementXML { get; set; } // text(max)
    }

    [Table("t_xref")]
    public partial class t_xrefs
    {
        [PrimaryKey, NotNull] public string XrefID { get; set; } // text(max)
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string Visibility { get; set; } // text(max)
        [Column, Nullable] public string Namespace { get; set; } // text(max)
        [Column, Nullable] public string Requirement { get; set; } // text(max)
        [Column, Nullable] public string Constraint { get; set; } // text(max)
        [Column, Nullable] public string Behavior { get; set; } // text(max)
        [Column, Nullable] public string Partition { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public string Client { get; set; } // text(max)
        [Column, Nullable] public string Supplier { get; set; } // text(max)
        [Column, Nullable] public string Link { get; set; } // text(max)
    }

    [Table("t_xrefsystem")]
    public partial class t_xrefsystems
    {
        [PrimaryKey, NotNull] public string XrefID { get; set; } // text(max)
        [Column, Nullable] public string ToolID { get; set; } // text(max)
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string Visibility { get; set; } // text(max)
        [Column, Nullable] public string Namespace { get; set; } // text(max)
        [Column, Nullable] public string Requirement { get; set; } // text(max)
        [Column, Nullable] public string Constraint { get; set; } // text(max)
        [Column, Nullable] public string Behavior { get; set; } // text(max)
        [Column, Nullable] public string Partition { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public string Client { get; set; } // text(max)
        [Column, Nullable] public string Supplier { get; set; } // text(max)
        [Column, Nullable] public string Link { get; set; } // text(max)
    }

    [Table("t_xrefuser")]
    public partial class t_xrefusers
    {
        [PrimaryKey, NotNull] public string XrefID { get; set; } // text(max)
        [Column, Nullable] public string ToolID { get; set; } // text(max)
        [Column, Nullable] public string Name { get; set; } // text(max)
        [Column, Nullable] public string Type { get; set; } // text(max)
        [Column, Nullable] public string Visibility { get; set; } // text(max)
        [Column, Nullable] public string Namespace { get; set; } // text(max)
        [Column, Nullable] public string Requirement { get; set; } // text(max)
        [Column, Nullable] public string Constraint { get; set; } // text(max)
        [Column, Nullable] public string Behavior { get; set; } // text(max)
        [Column, Nullable] public string Partition { get; set; } // text(max)
        [Column, Nullable] public string Description { get; set; } // text(max)
        [Column, Nullable] public string Client { get; set; } // text(max)
        [Column, Nullable] public string Supplier { get; set; } // text(max)
        [Column, Nullable] public string Link { get; set; } // text(max)
    }

    [Table("usys_schema")]
    public partial class usys_schemata
    {
        [PrimaryKey, NotNull] public string V1558 { get; set; } // text(max)
    }

    [Table("usys_system")]
    public partial class usys_systems
    {
        [PrimaryKey, NotNull] public string Property { get; set; } // text(max)
        [Column, Nullable] public string Value { get; set; } // text(max)
    }

    [Table("usysOldTables")]
    public partial class usysOldTables
    {
        [Column, Nullable] public string TableName { get; set; } // text(max)
        [Column, Nullable] public string NewName { get; set; } // text(max)
        [Column, Nullable] public long? RelOrder { get; set; } // integer
        [Column, Nullable] public long? FixCode { get; set; } // integer
    }

    [Table("usysQueries")]
    public partial class usysQueries
    {
        [Column, Nullable] public string QueryName { get; set; } // text(max)
        [Column, Nullable] public string NewName { get; set; } // text(max)
        [Column, Nullable] public long? FixCode { get; set; } // integer
    }

    [Table("usysTables")]
    public partial class usysTables
    {
        [PrimaryKey, NotNull] public string TableName { get; set; } // text(max)
        [Column, Nullable] public long? RelOrder { get; set; } // integer
        [Column, Nullable] public string DisplayName { get; set; } // text(max)
        [Column, Nullable] public string FromVer { get; set; } // text(max)
        [Column, Nullable] public string ToVer { get; set; } // text(max)
    }

    public static partial class TableExtensions
    {
        public static t_attributeconstraints Find(this ITable<t_attributeconstraints> table, string Constraint, long ID)
        {
            return table.FirstOrDefault(t =>
                t.Constraint == Constraint &&
                t.ID == ID);
        }

        public static t_attributes Find(this ITable<t_attributes> table, long ID)
        {
            return table.FirstOrDefault(t =>
                t.ID == ID);
        }

        public static t_attributetags Find(this ITable<t_attributetags> table, long PropertyID)
        {
            return table.FirstOrDefault(t =>
                t.PropertyID == PropertyID);
        }

        public static t_authors Find(this ITable<t_authors> table, string AuthorName)
        {
            return table.FirstOrDefault(t =>
                t.AuthorName == AuthorName);
        }

        public static t_cardinalities Find(this ITable<t_cardinalities> table, string Cardinality)
        {
            return table.FirstOrDefault(t =>
                t.Cardinality == Cardinality);
        }

        public static t_categories Find(this ITable<t_categories> table, long CategoryID)
        {
            return table.FirstOrDefault(t =>
                t.CategoryID == CategoryID);
        }

        public static t_clients Find(this ITable<t_clients> table, string Name)
        {
            return table.FirstOrDefault(t =>
                t.Name == Name);
        }

        public static t_complexitytypes Find(this ITable<t_complexitytypes> table, string Complexity)
        {
            return table.FirstOrDefault(t =>
                t.Complexity == Complexity);
        }

        public static t_connectorconstraints Find(this ITable<t_connectorconstraints> table, long ConnectorID, string Constraint)
        {
            return table.FirstOrDefault(t =>
                t.ConnectorID == ConnectorID &&
                t.Constraint == Constraint);
        }

        public static t_connectors Find(this ITable<t_connectors> table, long Connector_ID)
        {
            return table.FirstOrDefault(t =>
                t.Connector_ID == Connector_ID);
        }

        public static t_connectortags Find(this ITable<t_connectortags> table, long PropertyID)
        {
            return table.FirstOrDefault(t =>
                t.PropertyID == PropertyID);
        }

        public static t_connectortypes Find(this ITable<t_connectortypes> table, string Connector_Type)
        {
            return table.FirstOrDefault(t =>
                t.Connector_Type == Connector_Type);
        }

        public static t_constants Find(this ITable<t_constants> table, string ConstantName)
        {
            return table.FirstOrDefault(t =>
                t.ConstantName == ConstantName);
        }

        public static t_constrainttypes Find(this ITable<t_constrainttypes> table, string Constraint)
        {
            return table.FirstOrDefault(t =>
                t.Constraint == Constraint);
        }

        public static t_datatypes Find(this ITable<t_datatypes> table, long DatatypeID)
        {
            return table.FirstOrDefault(t =>
                t.DatatypeID == DatatypeID);
        }

        public static t_diagramlinks Find(this ITable<t_diagramlinks> table, long Instance_ID)
        {
            return table.FirstOrDefault(t =>
                t.Instance_ID == Instance_ID);
        }

        public static t_diagramobjects Find(this ITable<t_diagramobjects> table, long Instance_ID)
        {
            return table.FirstOrDefault(t =>
                t.Instance_ID == Instance_ID);
        }

        public static t_diagrams Find(this ITable<t_diagrams> table, long Diagram_ID)
        {
            return table.FirstOrDefault(t =>
                t.Diagram_ID == Diagram_ID);
        }

        public static t_diagramtypes Find(this ITable<t_diagramtypes> table, string Diagram_Type)
        {
            return table.FirstOrDefault(t =>
                t.Diagram_Type == Diagram_Type);
        }

        public static t_documents Find(this ITable<t_documents> table, string DocID)
        {
            return table.FirstOrDefault(t =>
                t.DocID == DocID);
        }

        public static t_ecfs Find(this ITable<t_ecfs> table, string ECFID)
        {
            return table.FirstOrDefault(t =>
                t.ECFID == ECFID);
        }

        public static t_efforttypes Find(this ITable<t_efforttypes> table, string EffortType)
        {
            return table.FirstOrDefault(t =>
                t.EffortType == EffortType);
        }

        public static t_files Find(this ITable<t_files> table, string FileID)
        {
            return table.FirstOrDefault(t =>
                t.FileID == FileID);
        }

        public static t_glossaries Find(this ITable<t_glossaries> table, long GlossaryID)
        {
            return table.FirstOrDefault(t =>
                t.GlossaryID == GlossaryID);
        }

        public static t_images Find(this ITable<t_images> table, long ImageID)
        {
            return table.FirstOrDefault(t =>
                t.ImageID == ImageID);
        }

        public static t_issues Find(this ITable<t_issues> table, long IssueID)
        {
            return table.FirstOrDefault(t =>
                t.IssueID == IssueID);
        }

        public static t_lists Find(this ITable<t_lists> table, string ListID)
        {
            return table.FirstOrDefault(t =>
                t.ListID == ListID);
        }

        public static t_mainttypes Find(this ITable<t_mainttypes> table, string MaintType)
        {
            return table.FirstOrDefault(t =>
                t.MaintType == MaintType);
        }

        public static t_methods Find(this ITable<t_methods> table, long Object_ID, string Name)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID &&
                t.Name == Name);
        }

        public static t_metrictypes Find(this ITable<t_metrictypes> table, string Metric)
        {
            return table.FirstOrDefault(t =>
                t.Metric == Metric);
        }

        public static t_objectconstraints Find(this ITable<t_objectconstraints> table, long Object_ID, string Constraint, string ConstraintType)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID &&
                t.Constraint == Constraint &&
                t.ConstraintType == ConstraintType);
        }

        public static t_objectefforts Find(this ITable<t_objectefforts> table, long Object_ID, string Effort)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID &&
                t.Effort == Effort);
        }

        public static t_objectfiles Find(this ITable<t_objectfiles> table, long Object_ID, string FileName)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID &&
                t.FileName == FileName);
        }

        public static t_objectmetrics Find(this ITable<t_objectmetrics> table, long Object_ID, string Metric)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID &&
                t.Metric == Metric);
        }

        public static t_objectproblems Find(this ITable<t_objectproblems> table, long Object_ID, string Problem, string ProblemType)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID &&
                t.Problem == Problem &&
                t.ProblemType == ProblemType);
        }

        public static t_objectproperties Find(this ITable<t_objectproperties> table, long PropertyID)
        {
            return table.FirstOrDefault(t =>
                t.PropertyID == PropertyID);
        }

        public static t_objectrequires Find(this ITable<t_objectrequires> table, long ReqID)
        {
            return table.FirstOrDefault(t =>
                t.ReqID == ReqID);
        }

        public static t_objectresources Find(this ITable<t_objectresources> table, long Object_ID, string Resource, string Role)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID &&
                t.Resource == Resource &&
                t.Role == Role);
        }

        public static t_objectrisks Find(this ITable<t_objectrisks> table, long Object_ID, string Risk)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID &&
                t.Risk == Risk);
        }

        public static t_objects Find(this ITable<t_objects> table, long Object_ID)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID);
        }

        public static t_objectscenarios Find(this ITable<t_objectscenarios> table, long Object_ID, string Scenario)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID &&
                t.Scenario == Scenario);
        }

        public static t_objecttests Find(this ITable<t_objecttests> table, long Object_ID, string Test, long TestClass)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID &&
                t.Test == Test &&
                t.TestClass == TestClass);
        }

        public static t_objecttrxes Find(this ITable<t_objecttrxes> table, long Object_ID, string TRX, string TRXType)
        {
            return table.FirstOrDefault(t =>
                t.Object_ID == Object_ID &&
                t.TRX == TRX &&
                t.TRXType == TRXType);
        }

        public static t_objecttypes Find(this ITable<t_objecttypes> table, string Object_Type)
        {
            return table.FirstOrDefault(t =>
                t.Object_Type == Object_Type);
        }

        public static t_operationparams Find(this ITable<t_operationparams> table, long OperationID, string Name)
        {
            return table.FirstOrDefault(t =>
                t.OperationID == OperationID &&
                t.Name == Name);
        }

        public static t_operationposts Find(this ITable<t_operationposts> table, long OperationID, string PostCondition)
        {
            return table.FirstOrDefault(t =>
                t.OperationID == OperationID &&
                t.PostCondition == PostCondition);
        }

        public static t_operationpres Find(this ITable<t_operationpres> table, long OperationID, string PreCondition)
        {
            return table.FirstOrDefault(t =>
                t.OperationID == OperationID &&
                t.PreCondition == PreCondition);
        }

        public static t_operations Find(this ITable<t_operations> table, long OperationID)
        {
            return table.FirstOrDefault(t =>
                t.OperationID == OperationID);
        }

        public static t_operationtags Find(this ITable<t_operationtags> table, long PropertyID)
        {
            return table.FirstOrDefault(t =>
                t.PropertyID == PropertyID);
        }

        public static t_packages Find(this ITable<t_packages> table, long Package_ID)
        {
            return table.FirstOrDefault(t =>
                t.Package_ID == Package_ID);
        }

        public static t_palettes Find(this ITable<t_palettes> table, long PaletteID)
        {
            return table.FirstOrDefault(t =>
                t.PaletteID == PaletteID);
        }

        public static t_phases Find(this ITable<t_phases> table, string PhaseID)
        {
            return table.FirstOrDefault(t =>
                t.PhaseID == PhaseID);
        }

        public static t_primitives Find(this ITable<t_primitives> table, string Datatype)
        {
            return table.FirstOrDefault(t =>
                t.Datatype == Datatype);
        }

        public static t_problemtypes Find(this ITable<t_problemtypes> table, string ProblemType)
        {
            return table.FirstOrDefault(t =>
                t.ProblemType == ProblemType);
        }

        public static t_projectroles Find(this ITable<t_projectroles> table, string Role)
        {
            return table.FirstOrDefault(t =>
                t.Role == Role);
        }

        public static t_propertytypes Find(this ITable<t_propertytypes> table, string Property)
        {
            return table.FirstOrDefault(t =>
                t.Property == Property);
        }

        public static t_requiretypes Find(this ITable<t_requiretypes> table, string Requirement)
        {
            return table.FirstOrDefault(t =>
                t.Requirement == Requirement);
        }

        public static t_resources Find(this ITable<t_resources> table, string Name)
        {
            return table.FirstOrDefault(t =>
                t.Name == Name);
        }

        public static t_risktypes Find(this ITable<t_risktypes> table, string Risk)
        {
            return table.FirstOrDefault(t =>
                t.Risk == Risk);
        }

        public static t_roleconstraints Find(this ITable<t_roleconstraints> table, long ConnectorID, string Constraint, string ConnectorEnd, string ConstraintType)
        {
            return table.FirstOrDefault(t =>
                t.ConnectorID == ConnectorID &&
                t.Constraint == Constraint &&
                t.ConnectorEnd == ConnectorEnd &&
                t.ConstraintType == ConstraintType);
        }

        public static t_rtfreports Find(this ITable<t_rtfreports> table, string TemplateID)
        {
            return table.FirstOrDefault(t =>
                t.TemplateID == TemplateID);
        }

        public static t_rules Find(this ITable<t_rules> table, string RuleID)
        {
            return table.FirstOrDefault(t =>
                t.RuleID == RuleID);
        }

        public static t_scenariotypes Find(this ITable<t_scenariotypes> table, string ScenarioType)
        {
            return table.FirstOrDefault(t =>
                t.ScenarioType == ScenarioType);
        }

        public static t_scripts Find(this ITable<t_scripts> table, long ScriptID)
        {
            return table.FirstOrDefault(t =>
                t.ScriptID == ScriptID);
        }

        public static t_secgrouppermissions Find(this ITable<t_secgrouppermissions> table, string GroupID, long PermissionID)
        {
            return table.FirstOrDefault(t =>
                t.GroupID == GroupID &&
                t.PermissionID == PermissionID);
        }

        public static t_secgroups Find(this ITable<t_secgroups> table, string GroupID)
        {
            return table.FirstOrDefault(t =>
                t.GroupID == GroupID);
        }

        public static t_seclocks Find(this ITable<t_seclocks> table, string EntityID)
        {
            return table.FirstOrDefault(t =>
                t.EntityID == EntityID);
        }

        public static t_secpermissions Find(this ITable<t_secpermissions> table, long PermissionID)
        {
            return table.FirstOrDefault(t =>
                t.PermissionID == PermissionID);
        }

        public static t_secpolicies Find(this ITable<t_secpolicies> table, string Property)
        {
            return table.FirstOrDefault(t =>
                t.Property == Property);
        }

        public static t_secusergroups Find(this ITable<t_secusergroups> table, string UserID, string GroupID)
        {
            return table.FirstOrDefault(t =>
                t.UserID == UserID &&
                t.GroupID == GroupID);
        }

        public static t_secuserpermissions Find(this ITable<t_secuserpermissions> table, string UserID, long PermissionID)
        {
            return table.FirstOrDefault(t =>
                t.UserID == UserID &&
                t.PermissionID == PermissionID);
        }

        public static t_secusers Find(this ITable<t_secusers> table, string UserID)
        {
            return table.FirstOrDefault(t =>
                t.UserID == UserID);
        }

        public static t_snapshots Find(this ITable<t_snapshots> table, string SnapshotID)
        {
            return table.FirstOrDefault(t =>
                t.SnapshotID == SnapshotID);
        }

        public static t_statustypes Find(this ITable<t_statustypes> table, string Status)
        {
            return table.FirstOrDefault(t =>
                t.Status == Status);
        }

        public static t_stereotypes Find(this ITable<t_stereotypes> table, string Stereotype, string AppliesTo)
        {
            return table.FirstOrDefault(t =>
                t.Stereotype == Stereotype &&
                t.AppliesTo == AppliesTo);
        }

        public static t_taggedvalues Find(this ITable<t_taggedvalues> table, string PropertyID)
        {
            return table.FirstOrDefault(t =>
                t.PropertyID == PropertyID);
        }

        public static t_tasks Find(this ITable<t_tasks> table, long TaskID)
        {
            return table.FirstOrDefault(t =>
                t.TaskID == TaskID);
        }

        public static t_tcfs Find(this ITable<t_tcfs> table, string TCFID)
        {
            return table.FirstOrDefault(t =>
                t.TCFID == TCFID);
        }

        public static t_templates Find(this ITable<t_templates> table, string TemplateID)
        {
            return table.FirstOrDefault(t =>
                t.TemplateID == TemplateID);
        }

        public static t_testclasses Find(this ITable<t_testclasses> table, string TestClass)
        {
            return table.FirstOrDefault(t =>
                t.TestClass == TestClass);
        }

        public static t_testplans Find(this ITable<t_testplans> table, string PlanID)
        {
            return table.FirstOrDefault(t =>
                t.PlanID == PlanID);
        }

        public static t_testtypes Find(this ITable<t_testtypes> table, string TestType)
        {
            return table.FirstOrDefault(t =>
                t.TestType == TestType);
        }

        public static t_trxtypes Find(this ITable<t_trxtypes> table, long TRX_ID)
        {
            return table.FirstOrDefault(t =>
                t.TRX_ID == TRX_ID);
        }

        public static t_umlpatterns Find(this ITable<t_umlpatterns> table, long PatternID)
        {
            return table.FirstOrDefault(t =>
                t.PatternID == PatternID);
        }

        public static t_versions Find(this ITable<t_versions> table, string ElementID, string VersionID)
        {
            return table.FirstOrDefault(t =>
                t.ElementID == ElementID &&
                t.VersionID == VersionID);
        }

        public static t_xrefs Find(this ITable<t_xrefs> table, string XrefID)
        {
            return table.FirstOrDefault(t =>
                t.XrefID == XrefID);
        }

        public static t_xrefsystems Find(this ITable<t_xrefsystems> table, string XrefID)
        {
            return table.FirstOrDefault(t =>
                t.XrefID == XrefID);
        }

        public static t_xrefusers Find(this ITable<t_xrefusers> table, string XrefID)
        {
            return table.FirstOrDefault(t =>
                t.XrefID == XrefID);
        }

        public static usys_schemata Find(this ITable<usys_schemata> table, string V1558)
        {
            return table.FirstOrDefault(t =>
                t.V1558 == V1558);
        }

        public static usys_systems Find(this ITable<usys_systems> table, string Property)
        {
            return table.FirstOrDefault(t =>
                t.Property == Property);
        }

        public static usysTables Find(this ITable<usysTables> table, string TableName)
        {
            return table.FirstOrDefault(t =>
                t.TableName == TableName);
        }
    }
}
